# Generated by Django 4.0.6 on 2022-08-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='author',
        ),
    ]
