# Generated by Django 4.2.1 on 2023-05-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0007_alter_post_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
