# Generated by Django 4.2.1 on 2023-06-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0011_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='masterpost',
        ),
    ]
