# Generated by Django 4.2.1 on 2023-06-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0012_rename_post_comment_masterpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='masterpost',
            new_name='masterPost',
        ),
    ]
