# Generated by Django 4.2.1 on 2023-06-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0014_post_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='masterPost',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments_linkedtothispost', to='api_basic.post'),
        ),
    ]
