# Generated by Django 4.2.1 on 2023-06-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0015_alter_comment_masterpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='masterPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_linkedtothispost', to='api_basic.post'),
        ),
    ]
